name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@af17d8ce986da0b92cbdfc84d2170e199e34a3fb # main
